#ifndef BOARDCONFIG_H
#define BOARDCONFIG_H

// LEDs: PJ.0-3, P3.4-7
#define LEDPORT1DIR P1DIR
#define LEDPORT1OUT P1OUT
#define LEDPORT1PIN0 BIT0

#define LEDPORT4DIR P4DIR
#define LEDPORT4OUT P4OUT
#define LEDPORT4PIN0 BIT0

#define CONSOLEUARTPORTSEL P1SEL0
#define CONSOLEUARTRXPIN BIT1
#define CONSOLEUARTTXPIN BIT0

#endif